### ISSUE TITLE
Password type

### ISSUE THREAD

**Issue by pquerner** [tkambler/electron-preferences#10]
Is it possible to add password type? Which is switched from cleartext to circles like in a normal UI, and also encrypted in the .json file afterwards?

**Comment by pvrobays** [comment]
Hi @pquerner 
Yes, it is possible to add a password type field. However it is not recommended to save sensitive data via electron-preferences. As the JSON will always be in plain text.
An example of how this can be accomplished:
```
{
    'label': 'Password',
    'key': 'password',
    'type': 'text',
    'inputType': 'password',
    'help': 'What is your password? (not encrypted)'
}
```

Encrypting the .json file would be a struggle. This would have to be a two way encryption algorithm, and will always be insecure as the key for this encryption algorithm would be stored somewhere in your javascript.
