### ISSUE TITLE
preferences.show() does not focus the window once created

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#101]
`preferences.show()` should really be called `preferences.create()`, since if the window already exists it doesn't do anything.

Fixing #95 would allow a workaround here, but calling preferences.show() should bring focus to the preferences window.

Currently if the window is open it can get lost behind other app windows with no way of programmatically providing focus

**Comment by pvrobays** [comment]
Fixed in v2.4.1
