### ISSUE TITLE
Non-field components: text, image, button

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#102]
**Is your feature request related to a problem? Please describe.**
I would like to add more helper text and content that is not related to an input or field.

**Describe the solution you'd like**
A text component that is purely aesthetic, does not correspond to any field or value
A button component that can have custom function, #99

**Comment by pvrobays** [comment]
@lacymorrow Is the `message` type a possibility for your 'text component that is purely aesthetic'?
```
{
    heading: 'Important Message',
    content: '<p>The quick brown fox jumps over the long white fence. The quick brown fox jumps over the long white fence. The quick brown fox jumps over the long white fence. The quick brown fox jumps over the long white fence.</p>',
    type: 'message',
},
```

**Comment by lacymorrow** [comment]
I think that’s exactly it, I looked right past it.
