### ISSUE TITLE
Expose windows overrides object to allow changes before showing the window

### ISSUE THREAD

**Issue by lvcabral** [tkambler/electron-preferences#112]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `electron-preferences@2.3.2` for the project I'm working on.

I just wanted to make sure that the Preferences window would show in the same monitor than the main application, and the way I managed that was to set the **x** and **y** correctly on  `options.browserWindowOverrides`. But this needs to happen every time the `show()` method is called, so exposiing it is necessary.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/electron-preferences/index.js b/node_modules/electron-preferences/index.js
index babcbc9..aee6e8d 100644
--- a/node_modules/electron-preferences/index.js
+++ b/node_modules/electron-preferences/index.js
@@ -113,6 +113,10 @@ class ElectronPreferences extends EventEmitter2 {
 
     }
 
+    get browserWindowOverrides() {
+        return this.options.browserWindowOverrides; 
+    }
+
     get preferences() {
 
         return this._preferences;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by pvrobays** [comment]
Hi @lvcabral 

Thanks for informing us of your manual adaptations.

We can definitely expose the `browserWindowOverrides` so people can make changes to them as they like during the lifetime of their application. We'll add this in the next release.

However for your solution it might seem more intuitive to pass the correct `parent` BrowserWindow to the browserWindowOverrides. Then we just need to check the position of the parent window, and adjust the preference window accordingly when the `.show()` method was triggered.

Would this last solution better suit your needs? Or did you have an even more elegant solution in mind?

**Comment by lvcabral** [comment]
> Hi @lvcabral
> 
> Thanks for informing us of your manual adaptations.
> 
> We can definitely expose the `browserWindowOverrides` so people can make changes to them as they like during the lifetime of their application. We'll add this in the next release.
> 
> However for your solution it might seem more intuitive to pass the correct `parent` BrowserWindow to the browserWindowOverrides. Then we just need to check the position of the parent window, and adjust the preference window accordingly when the `.show()` method was triggered.
> 
> Would this last solution better suit your needs? Or did you have an even more elegant solution in mind?

I'm setting the parent already but how can I adjust the position of the preferences window? The only way I found was this.

**Comment by lacymorrow** [comment]
This is related to #93, you can use `setBounds()` to move the browserWindow around. The recent addition allows you to do:

 ```js
// start of electron main
const ElectronPreferences = require( 'electron-preferences' )
const preferences = new ElectronPreferences(/*... All the stuff */)
let preferencesWindow;
// ...
const createPreferencesWindow = () => {
	preferencesWindow = preferences.show()
 	// Now you have an instance of the preferences browserWindow
	// you can call .setBounds()
}
```

we really need to add a getter method for the `preferencesWindow` object, and then you'll be able to have access to the window without relying on saving during `.show()`.

**Comment by lvcabral** [comment]
Thanks @lacymorrow for the feedback, I was not aware of this new feature. I managed to make it work, but I still think this is no the ideal, as I'm moving the window after the .show() was issued, fortunately (at least in Windows) it is not noticeable any movement of the child window. I will test later on Linux and Mac. We still need to have a way to do this before the .show().

**Comment by pvrobays** [comment]
@lvcabral `preferences.browserWindowOverrides` will be exposed in the next release! (#127)
