### ISSUE TITLE
Not being built properly when adding to project

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#113]
What am I doing wrong? I can add a local folder to my `package.json` like: 
![image](https://user-images.githubusercontent.com/1311301/125892331-2581c3f9-36c3-42db-85ca-146e9eac5dc4.png)

but if I try to use the actual library, it doesn't have the `build` folder and my app doesn't load.

**Comment by pvrobays** [comment]
@lacymorrow That's not good!
I've checked the npm package, it does contain the `build` folder and seems to have all the necessary files included.

What is the actual problem you're having? The electron build fails? webpack build failure?

Be sure to try and remove your `packages.lock.json` file and rerun `npm install`. Maybe that helps.

**Comment by lacymorrow** [comment]
i'm not sure what I was doing wrong! The settings window would display with a white background and no content.

I tried again and it worked, if someone has this issue:
`rm yarn.lock`
`yarn remove electron-preferences`
`yarn add electron-preferences`
