### ISSUE TITLE
preferences.show not defined?

### ISSUE THREAD

**Issue by JeremyRubin** [tkambler/electron-preferences#120]
I set up the preferences as per the readme, and the preference object exists, but there's no method preferences.show.

e.g., console.log(preferences) outputs

```
{
  notes: { folder: '/Users/jr/Notes' },
  markdown: { auto_format_links: true, show_gutter: false },
  preview: { show: true },
  drawer: { show: true }
}
```

but calling preferences.show() yields an error.

**Comment by JeremyRubin** [comment]
fixed:

```js
//bad
module.exports = preferences;
//good
module.exports = {preferences: preferences};
```

**Comment by JeremyRubin** [comment]
this seems to be a consistent problem that preference coerces to a flat object instead of the Class. this is caused by a getter in preferences for preferences which seems to cause the buggy resolution/casting

this is fixed by 

```js
//bad
module.exports = preferences;
// also bad
module.exports = {preferences: preferences};
// at last, good
module.exports = {settings: preferences};
```

**Comment by pvrobays** [comment]
Hi @JeremyRubin 
First of all, my apologies for the late response.

The code in the readme (which is a subset of the example code) should work fine?
via `const ElectronPreferences = require('electron-preferences');` you'll get access to the ElectronPreferences class.
```
const preferences = new ElectronPreferences({
    // ...
});
```
This will give you an instance of ElectronPreferences with your passed options. On this object you can start calling the `.show()` function etc.

Could you please provide the code you've used as setup? That way we can check if we need to adapt something in the README.


ℹ We might want to add the more modern import pattern to the README: `import ElectronPreferences from "electron-preferences"`

**Comment by JeremyRubin** [comment]
no worries -- open source software, you don't owe me your time :)

you can see the project here https://github.com/sapio-lang/sapio-studio. This issue comes up anytime I do any of the bad export patterns for the preference object that I create. I think it might be an underlying JS issue that:

`module.exports = preferences;` and a `const preferences = require(...);` results in a resolution conflict when preferences also has a getter named preferences, somehow I think resolution gets confused.

The simplest thing to make sure this issue doesn't come up is to just change the readme so that you don't tell users to name their preferences object something that overlaps with a getter.

**Comment by JeremyRubin** [comment]
(I no longer have this issue BTW, but someone else might have a similar problem come up in the future).

**Comment by pvrobays** [comment]
Hi @JeremyRubin 
I'm still not completely up to speed with the problem you had. Do you still have the full original code of the issue? 

Of what I now see, it looks like you're just overwriting the preferences variable's scope?

**Comment by lacymorrow** [comment]
I _think_ he's referencing this getter/setter in index.js:
```js
	get preferences() {
		return this._preferences;
	}

	set preferences(value) {
		this._preferences = value;
	}
```

There can be some confusion with `preferences` being a class and `preferences.preferences` being the object: 
```js
const preferences = new ElectronPreferences({ // ... });
preferences // ...  the electron-preferences class
preferences.preferences // ... the preferences object
```
