### ISSUE TITLE
Add easy way to open dev tools

### ISSUE THREAD

**Issue by pvrobays** [tkambler/electron-preferences#124]
**Is your feature request related to a problem? Please describe.**
In production it's hard to open the dev tools.

**Describe the solution you'd like**
 An easy 'debug: true' statement in the properties should do the trick

**Comment by lacymorrow** [comment]
Yeah debug in production mode is discouraged. My preferred way if necessary is to add a file-menu item

**Comment by lacymorrow** [comment]
Close this :)

**Comment by pvrobays** [comment]
@lacymorrow File-menu is something that should be set/adapted by the end-user IMO. To have easy access for everybody, you can now use the debug option.
