### ISSUE TITLE
Clarification of changed in 2.5.0

### ISSUE THREAD

**Issue by coredev-uk** [tkambler/electron-preferences#129]
Can you please explain to me how this has changed: `Checkbox type supports a single boolean value`. I'm assuming that this means it no longer displays bools in arrays? If someone could just help me out with this that'd be great.

**Comment by pvrobays** [comment]
It should be completely backwards compatible. When the user changes a
checkbox via the electron-preferences UI it'll still be saved as an array
of the values, even if it's a single checkbox.
What changed is the behaviour when, for a single checkbox, the default
settings (or the current settings) don't contain an array but a boolean
value. In that case the single checkbox will either be checked (true) or
unchecked (false). But again, once the user changes the check of that
single checkbox, the value in the preferences.json will return to an array
of the values.

So I assume you shouldn't do any code changes to your current
implementation. If so, please let me know so we can take actions if
necessary.

**Comment by coredev-uk** [comment]
I think I understand, just to clarify for a checkbox if you set the default value to a bool that will represent whether it toggled (
true being toggled and false it being untoggled)?

**Comment by lacymorrow** [comment]
To be clear, the checkbox value is still stored as an Array, even with a single value.

The change that was made coerces a default value of `true` to `['key']` and `false` to `[]`

**Comment by coredev-uk** [comment]
I understand now, thanks.
