### ISSUE TITLE
Boolean values don't save as booleans

### ISSUE THREAD

**Issue by FlipABit** [tkambler/electron-preferences#13]
It seems that if I add a setting that offers a 'true' or 'false value, it ends up saving in the preferences file as a literal string value "true" or "false". for example:

```
sections: [
    {
      id: 'camera',
      label: 'Camera',
      icon: 'camera-20',
      form: {
        groups: [
          {
            label: 'Camera Access',
            fields: [
              {
                label: 'Allow Camera Access?',
                key: 'enabled',
                type: 'checkbox',
                options: [{ label: 'Yes', value: true }, { label: 'No', value: false }]
              }
            ]
          }
        ]
      }
    }
  ]
```

Results in a preferences file:
```
{
    "camera": {
        "enabled": "true"
    }
}
```

**Comment by pvrobays** [comment]
Hi @FlipABit. Thanks you for your contribution.
I've also encountered this issue in my project. It's indeed annoying that it saves the values as strings. I'll check what we can do about it.

I was also thinking of creating a 'switch' field, specific for boolean values. I'll keep you posted.

**Comment by lacymorrow** [comment]
Checkbox controls in general are handled with values as strings, so this is to be expected. This allows for multiple grouped checkboxes to maintain a single state of values like `['foo', 'bar']`.

It's not ideal in this case for booleans, but it is the expected behavior. As such, I believe this can be closed.

**Comment by pvrobays** [comment]
As discussed we won’t change this behaviour. Instead feature #54 has been created. This should create a switch field which handles boolean values.
Closing this issue.
