### ISSUE TITLE
Read only field?

### ISSUE THREAD

**Issue by exander77** [tkambler/electron-preferences#135]
Am I missing it in the documentation?

**Comment by pvrobays** [comment]
Read only fields isn't implemented. We do have a 'message' type which may help you?

Not sure if I can think of a decent use case where we should show read only fields in the preferences window to the user.

**Comment by exander77** [comment]
@pvrobays I use messages, but I don't think I can update its value, am I correct?

**Comment by pvrobays** [comment]
It is possible via the 'hack' of manipulating the preferences.options object directly.

But what is your exact use case? I still think it's a bit weird to show an end user a preference value, which he isn't able to change.

**Comment by exander77** [comment]
@pvrobays It was actually a workaround for this: https://github.com/tkambler/electron-preferences/issues/136

That I would have a text field and a drop-down menu for the same property.

**Comment by pvrobays** [comment]
OK, as I cannot think of a decent use case and you have been helped further, I'm closing this issue.
