### ISSUE TITLE
Injecting option based on previous value

### ISSUE THREAD

**Issue by exander77** [tkambler/electron-preferences#136]
I am listing serial devices, but I want to be able to show the device which is not currently available, I would need to access preferences before the preferences object is created to get the value and inject it into the options. Or Am I missing something?

**Comment by pvrobays** [comment]
Hi @exander77 

Not sure if I'm understanding your use case completely.
What you can perfectly do is create the preferences object, without showing the preferences window first. In that state you can programmatically get and set the preferences to whatever you want. Once you open the settings then, the updated preferences will be shown.

Copied from the docs:
```
// Get a value from the preferences data store
const myPref = preferences.value('some.nested.key');

// Save a value within the preferences data store
preferences.value('some.nested.key', 'my-value');
```

Hope this helps you.

**Comment by exander77** [comment]
@pvrobays But can I inject an option into the preference windows drop-down menu?

**Comment by pvrobays** [comment]
Well it isn't actually supported, but possible. The options field is available on the preference object, where you can navigate your way to whatever you want to change.
For example, to add an extra drop down item in the 'Gender' field in the 'About you' group of the example app:
```
preferences.options.sections.find(s => s.id === "about")?.form.groups.find(g => g.label === "About You")?.fields.find(f => f.label === "Gender")?.options.push(
	{ label: 'X', value: 'neutral' }
);
```

**Comment by exander77** [comment]
@pvrobays Great, that would work for me!

**Comment by dewiweb** [comment]
@pvrobays Do you think it's possible to use this way to modify the "help" field of an input dynamically?

**Comment by pvrobays** [comment]
hi @dewiweb

Depends on how 'dynamic' you want it.
If you change the object -as done in the comment above- before showing the preferences window, then that's perfectly possible. Changing it during the preferences window is opened, may be harder to accomplish.
