### ISSUE TITLE
Preferences Window shows MenuBar in Electron 6

### ISSUE THREAD

**Issue by davidsulpy** [tkambler/electron-preferences#18]
*Issue*: 
The Preferences Window will show a default MenuBar in the BrowserWindow when using Electron 6.

*Steps to repro*:
- install electron 6.0.7
- install electron-preferences 1.3.0
- create an ElectronPreferences object and call `.show()`

Notice on Windows, you'll see a menu bar atop the BrowserWindow. This is due to a behavior change introduced by the Electron team:
https://electronjs.org/docs/api/breaking-changes#winsetmenunull
Unless the BrowserWindow is passed opts that include frame specifications, a default menubar will show and that menu bar can only be removed by calling `BrowserWindow.removeMenu()`

*Suggested Change Options*:
1. Most Flexible: By allowing the library consumer to pass in BrowserWindow opts overrides, the library dependent could pass in `frame: false` into the BrowserWindow constructor opts to remove the MenuBar. (example in this PR: https://github.com/tkambler/electron-preferences/pull/17)
2. Less Flexible: Add `frame: false` to the options in the BrowserWindow constructor in the `show()` method.

**Comment by jamesremuscat** [comment]
Note to anyone else stumbling across this as I just did:

As of 8159717e, `electron-preferences` tries to remove the prefs window's menu bar unless you've explicitly set a `menuBar` option when constructing `ElectronPreferences`.

However, there's an outstanding Electron bug https://github.com/electron/electron/issues/16521 which means that `electron-preferences`'s call of `setMenu(null)` is ignored.

If you don't want a fully frameless window, to work around that bug you can call `electron.Menu.setApplicationMenu(null)` somewhere in your main process before your main window is created. (That obviously might have repercussions if you need the application menu to not be null!)

**Comment by davidsulpy** [comment]
@jamesremuscat I'm not sure I follow your note here. In your last paragraph did you mean to say "If you ~don't~ want a fully frameless window"?

**Comment by jamesremuscat** [comment]
> @jamesremuscat In your last paragraph did you mean to say "If you ~don't~ want a fully frameless window"?

No, what I wrote was correct.

If you're happy with a fully frameless preferences window, you can pass `frame: false` as suggested above, and you won't get a menu either.

If you want a normal-ish window that has a frame but not a menu, then it seems necessary to use the `setApplicationMenu` hack to remove the menu from the preferences window, since Electron currently doesn't honour the `setMenu(null)` call that `electron-preferences` makes.

Does that explain things any better?

**Comment by davidsulpy** [comment]
Ahh, I totally understand what you're saying now. Thank you for clarifying!
