### ISSUE TITLE
Bad "default" path example

### ISSUE THREAD

**Issue by thehans** [tkambler/electron-preferences#208]
**Describe the bug**
The README has some [example usage](https://github.com/snapcrunch/electron-preferences#from-the-main-process) which includes
```
dataStore: '~/preferences.json', // defaults to <userData>/preferences.json
```
This does not function as described.

**To Reproduce**
1. Try using the preference settings provided in the README
2. Run the app
3. Check your project top level folder and observe that a folder named `~` was created for `preferences.json`, instead of the claimed userData path.

This also creates the incredibly tense situation where attempting to remove the faulty path is one character away from wiping the user's home directory.  `rm -r \~/`

**Expected behavior**
Probably should say:
`dataStore: path.join(app.getPath("userData"), 'preferences.json'),`

Also, omitting `dataStore` results in `Error: The 'dataStore' option is required.`
So I would not say that it "defaults to" anything

**Machine (please complete the following information):**
 - OS: Linux Mint 21.2
 - Electron version: "26.2.1"
 - electron-preferences version: "2.8.2"

**Comment by pvrobays** [comment]
Hi @thehans 

Thanks for creating this issue.

It seems like you're one of our first linux users. I was under the impression that the `~/` path would point to the user's home directory.

I'll adapt the readme to use your proposed solution.
