### ISSUE TITLE
Create an event to allow detect that Preferences were updated

### ISSUE THREAD

**Issue by lvcabral** [tkambler/electron-preferences#213]
**Is your feature request related to a problem? Please describe.**
Enable the possibility to customize themes (not only system light and dark) for the Preferences screen.

**Describe the solution you'd like**
Create an event named `onPreferencesUpdated` in `preload.js` that will be triggered when preferences are udpated.

**Describe alternatives you've considered**
This only and more concise way I found to accomplish my need.

**Additional context**
My app is already using this solution with a patch for this repository, check the code at:
https://github.com/lvcabral/brs-emu-app

**Comment by lacymorrow** [comment]
@lvcabral I tweaked your code slightly, let me know if there are any issues.
