### ISSUE TITLE
this.prefsWindow.removeMenu not supported on Mac

### ISSUE THREAD

**Issue by boosey** [tkambler/electron-preferences#22]
Initialization in index.js calls this.prefsWindow.removeMenu and setMenu. This Electron API is not supported on Mac OS. Wrapping this code in a process.platform check fixes the problem.

` if (process.platform !== 'darwin') {
            if (this.options.menuBar) {
                this.prefsWindow.setMenu(this.options.menuBar);
            } else {
                this.prefsWindow.removeMenu();
            }
}`

**Comment by ednjv** [comment]
I also had this problem, thanks for pointing out the solution

It would be great if you could do a pull request with this

**Comment by ChinaShrimp** [comment]
+1

**Comment by defcon8** [comment]
+1
When is this fixed in the trunk?

**Comment by davidsulpy** [comment]
@boosey @ednjv did you experience an exception calling `setMenu` or `removeMenu` in MacOS? I didn't see an issue on mac myself, so just trying to recreate whatever issue you found. As far as I've seen, on MacOS it just results in a no-op, but perhaps I've missed something

**Comment by pvrobays** [comment]
Closing this issue. As @davidsulpy stated, no fix needed.
