### ISSUE TITLE
BrowserWindow's title can't be overriden

### ISSUE THREAD

**Issue by ednjv** [tkambler/electron-preferences#23]
If we set

```
new ElectronPreferences({
  dataStore: path.resolve(__dirname, 'preferences.json'),
  defaults: {
    markdown: {
      auto_format_links: true,
      show_gutter: false,
    },
    preview: {
      show: true,
    },
    drawer: {
      show: true,
    },
  },
  webPreferences: {
    devTools: false,
  },
  browserWindowOverrides: {
    title: 'Another thing',
  },
}
```

The `title`option gets ignored, this is because according to the [BrowserWindow](https://electronjs.org/docs/api/browser-window) docs

>title String (optional) - Default window title. Default is "Electron". If the HTML tag <title> is defined in the HTML file loaded by loadURL(), this property will be ignored.

And the `index.html` of the build has the `title` property defined

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Preferences</title>
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="css/vendor.css">
    </head>
    <body>
        <div class="window noselect" id="window"></div>
        <script src="js/vendor.js"></script>
        <script src="js/app.bundle.js"></script>
    </body>
</html>
```

Removing `<title>Preferences</title>` should be enough

**Comment by pvrobays** [comment]
Thanks @ednjv for the contribution.
I've created a new PR with your fix, as a part of your committed code had already been fixed.
