### ISSUE TITLE
Feature Request: onSave handler

### ISSUE THREAD

**Issue by pento** [tkambler/electron-preferences#5]
It'd be super useful to be able to pass an `onSave` handler when creating the `ElectronPreferences` object. 

This would allow the main process to perform tasks when preferences are changed.

**Comment by tkambler** [comment]
Great idea. If you’ll submit a PR, it would be reviewed quickly.

**Comment by tkambler** [comment]
I went ahead and implemented this. The `ElectronPreferences` class now emits a `save` event. See README.md for details.
