### ISSUE TITLE
Create a file type, for selecting specific files

### ISSUE THREAD

**Issue by pvrobays** [tkambler/electron-preferences#55]
Create a file type, for selecting specific files:

- images (jpg/png/...)
- runnable files (exe, dmg, ...)
- ...

**Comment by daryl-williams** [comment]
Hi Pieter-Jan,

Thank you for creating this issue. I will be glad to have a look and see if this is something I can do, unfortunately I do not really know the React framework so I will probably have some questions. I definitely appreciate your work and your help!

Thanks,

Daryl

**Comment by daryl-williams** [comment]
Hi Pieter-Jan,

I have reviewed the source code in the file: ./node_modules/electron-preferences/src/app/components/main/components/group/components/fields/directory/index.js to see what might be involved in making this work. I decided to copy the structure to a new sibling directory I called "file-select" and copied directory.js to the file-select directory as file-select.js and changed all references in the file from "directory" to "file".  I then tried to see if it might work but not surprisingly it did not. I Imagine there might be some sort of registration process or a build that might be required, but am totally at a loss as to how to proceed, or if I am even on the right track. Any thoughts or ideas would be much appreciated.

Thanks,

Daryl

**Comment by daryl-williams** [comment]
I have also added a file_selection entry to the fieldMap i the file: ./node_modules/electron-preferences/src/app/components/main/components/group/index.js so it looks like this:

```
import FileSelectField from './components/fields/file-select';

const fieldMap = {
    'file_select': FileSelectField,
    'directory': DirectoryField,
    'text': TextField,
    'message': MessageField,
    'dropdown': DropdownField,
    'checkbox': CheckboxField,
    'radio': RadioField,
    'slider': SliderField,
    'accelerator': AcceleratorField,
    'color': ColorField,
    'list': ListField
};

```
but still no luck. I will continue investigating.

Daryl

**Comment by pvrobays** [comment]
Hi @daryl-williams 
Sorry for the late reply, must have missed your comment notifications.

You were quite close, but you should always develop by cloning this github project first, and start developing from there :)

Meanwhile I've had some time and I've made a first implementation of the file type, it's on branch 'feature/file-selection' in this repo.
If you want, you can check it out on your PC and test if it works as you expected.

If you're not sure how to do it, in the [introduction](https://github.com/tkambler/electron-preferences#introduction) section are some commands you have to execute that'll help you set up the example project.

**Comment by pvrobays** [comment]
FYI, created PR #84 for this

**Comment by pvrobays** [comment]
Will be available in the next release
