### ISSUE TITLE
Hover states

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#56]
If a GUI doesn't match the system theme and doesn't use a `cursor: pointer`, controls like buttons need a hover state to indicate they are interactive.

**Comment by pvrobays** [comment]
Hi @lacymorrow 
Do you have an example of this? Which UI elements? Which OS/theme?
I don't think I'm fully getting what you're saying here.

**Comment by lacymorrow** [comment]
In the sidebar navigation, there is no indication that the buttons are interactive: 
![image](https://user-images.githubusercontent.com/1311301/112217053-757c9980-8bdf-11eb-8a70-07b32498b103.png)

**Comment by pvrobays** [comment]
Oh OK, that's indeed something I forgot. I'll fix it.

**Comment by pvrobays** [comment]
BTW, I like your 'Keybinds' icon 😅

**Comment by pvrobays** [comment]
Fixed. Will be available in the next release.
