### ISSUE TITLE
Write files atomically

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#58]
If node crashes during a file write, the preferences file may be corrupted.
Use something like https://github.com/fabiospampinato/atomically or even just use https://github.com/sindresorhus/electron-store (which uses `atomically`)

https://github.com/tkambler/electron-preferences/blob/858b77d918852a54bc378d7733fe3c1144220efa/index.js#L126

**Comment by pvrobays** [comment]
Valid point @lacymorrow.
Looks like you have some experience with atomically? Feel free to create a PR.
Otherwise I'll try to dig into their documentation and try to add it.
