### ISSUE TITLE
Missing build/index.html

### ISSUE THREAD

**Issue by stephenl03** [tkambler/electron-preferences#6]
When attempting to run the example, the preferences window opens, but in the console it gives an error...
```Not allowed to load local resource: file:///home/my_user/git_stuff/ep-test/build/index.html```
It looks like this folder was removed with commit c90d17d71b2125b5b1fcba4f0b31eb5f6efb1900 It is referenced here https://github.com/tkambler/electron-preferences/blob/master/index.js#L172

**Comment by tkambler** [comment]
You need to run this first:

```
npm run build
```

Thanks for the heads up. The readme has been updated.

**Comment by stephenl03** [comment]
`npm run build` still errors out for me as I don't have `compass` installed, so I had to add `--force` to this line.
https://github.com/tkambler/electron-preferences/blob/master/package.json#L17
