### ISSUE TITLE
Compatible with Electron 12

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#60]
Make sure you set `window.webPreferences.contextIsolation` soon:
```
(node:36051) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by pvrobays** [comment]
@lacymorrow Thanks for the heads up.

Meanwhile the example code should be refactored. The preload script still exposes the full ipcRenderer.

**Comment by pvrobays** [comment]
PR is open. I'll go over it tomorrow. If you want you can have a look. #67
