### ISSUE TITLE
Allow custom BrowserWindow settings

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#62]
Would be beneficial for folks who need to customize specific properties like `stayAlwaysOnTop`.
Most of these properties can be changed after the window is created so this may be a "nice-to-have"

**Comment by pvrobays** [comment]
Hi @lacymorrow

This is already possible via the `browserWindowOverrides` option. To see this in action, check out the example.

to have the `stayAlwaysOnTop` you would need to add the following:
```
const preferences = new ElectronPreferences({
    ...
   'browserWindowOverrides: {
        alwaysOnTop: true
    },
    ....
});
```
