### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#64]
FontAwesome is being bundled, why not allow all of the available icons?

**Comment by lacymorrow** [comment]
By the way, I apologize for all of the issues :)

**Comment by pvrobays** [comment]
Yeah, I've noticed the FontAwesome dependency after replacing the current icons...

TBH I've added the removal of FontAwesome to my to do list. I'm not really a fan as we definitely need to keep the current interface working with the (very specific) naming of the icons (see readme.md)

**Comment by pvrobays** [comment]
Oh, and don't mind the issues. I'm glad other people want to contribute to this repo 😊

**Comment by lacymorrow** [comment]
I'd rather contribute than rebuild. I'd agree with the removal of fontAwesome and as many dependencies as possible. I'll keep making suggestions, cheers!
