### ISSUE TITLE
Accelerator setting is incorrect

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#66]
This should be `alt+p`: 
![image](https://user-images.githubusercontent.com/1311301/112217309-b70d4480-8bdf-11eb-806c-3eb8377056e8.png)

As always, probably better to use a library like mousetrap or hotkey.js for this.

**Comment by pvrobays** [comment]
Yeah, true. The endless pain of handling key events in web development...
I'll take a look once I have the time.
FYI: on a qwerty windows machine you can use `ctrl + alt + r` which will show `Control+Alt+®`

**Comment by lacymorrow** [comment]
Started work on this
