### ISSUE TITLE
Can you help to get / set the notifications system Preferences ? (especially on OSX)

### ISSUE THREAD

**Issue by Aarbel** [tkambler/electron-preferences#69]
Does yourlibrary can provide a way to manage notifications system preferences from the app ? (or at last knowing which is the  notification system preference)

**Comment by pvrobays** [comment]
No sorry, that's not the purpose of this library.
You can however use this library for displaying the different settings, but
you'll have to get the notification settings yourself and push them to the
library. Once these settings are saved, you should handle those changes and
push them to the notification api.
TBH I'm not familiar with the electron notification API so I can't help you
with that. The electron documentation should be a good reference though.

**Comment by pvrobays** [comment]
FYI @Aarbel https://www.electronjs.org/docs/api/notification
If I get what you're saying, this should help you on your way.

Closing this issue for now.
