### ISSUE TITLE
Warning: not found: compass Use --force to continue.

### ISSUE THREAD

**Issue by daryl-williams** [tkambler/electron-preferences#71]
I am trying to use electron-preferences in an application but am getting the following error:

```
Warning: not found: compass Use --force to continue.

Aborted due to warnings.
npm ERR! code 3
npm ERR! path /Users/daryl/Projects/Electron/electron-preferences
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daryl/.npm/_logs/2021-04-25T17_51_48_353Z-debug.log

```
Any help would be greatly appreciated, thanks!

Regards,

Daryl

**Comment by pvrobays** [comment]
Hi @daryl-williams 
Building electron-preferences currently has a dependency on 'compass' (there's issue #63 which will resolve that).
So if you want to build the project yourself, you should install compass (https://rubygems.org/gems/compass/) and ruby (if not yet installed: https://www.ruby-lang.org/en/documentation/installation/)

However, if you just want to use electron-preferences in your current project, I suggest installing the prebuild versions via NPM.
Just run `npm install electron-preferences` in your project folder.
