### ISSUE TITLE
Preference window without menu

### ISSUE THREAD

**Issue by daryl-williams** [tkambler/electron-preferences#78]
Hello Folks,
I am pretty new to Electron and to electron-preferences so this may be a pretty silly question, but here goes. I have defined an application menu for my main window but now when I bring up the preferences window it also has the menu. Is there someway for the prererences window not to have a menu?

Thanks,

Daryl

**Comment by pvrobays** [comment]
Hi @daryl-williams 

TBH I thought this already was the case when you didn't pass the `menuBar` option to the preference constructor. But it could be the case that application menus override this option. Can't find anything on this in the electron documentation.

When I find the time, I'll try this out myself if there's some workaround and get back to you.
If you want you can have a look yourself already? The part where we remove the menu bar can be found [here](https://github.com/tkambler/electron-preferences/blob/7f8a17fd0059246a312649c59e35ac753a1c95a6/index.js#L207) in the code.

Pieter-Jan

**Comment by pvrobays** [comment]
Meanwhile found the time to have a quick look at this.

Seems like the statement I've made above is correct. The menu bar is removed on the creation of the preference window. So if you don't pass a `menuBar` option, there shouldn't be a menu bar.

However, if you set the `applicationMenuBar` after the preference window has been initialized, that new menu bar will also be shown in the preference window.

So the solution in your case will be to trigger the `Menu.setApplicationMenu(menu)` before you create the preference window, and don't trigger it again while the preference window has been opened.

The example code I've tested with:
It creates an application menu bar, shows the preference window (without a menu bar); then after 5s it again sets the application menu bar and that one will also be shown in the preference window.

main.js
```
'use strict';

const electron = require('electron');
const app = electron.app;
const nativeTheme = electron.nativeTheme;
const BrowserWindow = electron.BrowserWindow;
const path = require('path');
const url = require('url');

const preferences = require('./preferences');

nativeTheme.themeSource = preferences.preferences?.theme?.theme ?? "system";

preferences.on('save', (preferences) => {
    console.log(`Preferences were saved.`, JSON.stringify(preferences, null, 4));

    nativeTheme.themeSource = preferences?.theme?.theme ?? "system";
});

let mainWindow;

function createWindow() {
    
    mainWindow = new BrowserWindow({
        'width': 1200,
        'height': 700,
        'accept-first-mouse': true,
        webPreferences: {
            preload: path.join(__dirname, './Preload.js'),
            contextIsolation: true
        }
    });

    mainWindow.loadURL(url.format({
        'pathname': path.join(__dirname, 'index.html'),
        'protocol': 'file:',
        'slashes': true
    }));

    // mainWindow.webContents.openDevTools();

    mainWindow.on('closed', function() {
        mainWindow = null;
    });


    const { Menu } = electron;
    const template = [
        {
            role: 'help',
            submenu: [
                {
                    label: 'Learn More',
                    click: async () => {
                        const { shell } = require('electron')
                        await shell.openExternal('https://electronjs.org')
                    }
                }
            ]
        }
    ]
    const menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
    
    setTimeout(() => {
        Menu.setApplicationMenu(menu);
    }, 5000);
}

app.on('ready', createWindow);

app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', function() {
    if (mainWindow === null) {
        createWindow();
    }
});
```

**Comment by pvrobays** [comment]
Closing this issue as this is already implemented
