### ISSUE TITLE
Using File Dialog in Preferences

### ISSUE THREAD

**Issue by daryl-williams** [tkambler/electron-preferences#80]
Folks,

I need to have the preferences window allow the user to bring up a file dialog window. I am unable to find any examples on how to do this. I was thinking of maybe using a link or button to a javascript function but am not familiar enough with the preferences "sections" to display a url to the user. Any help would be much appreciated.

Thanks,

Daryl

**Comment by pvrobays** [comment]
Hi Daryl

Sorry, apparently I've overlooked this issue. But if I'm not mistaken, this one can also be linked to #55 ?
FYI: the way this is now done in the 'directory' component, is by showing a button which opens the dialog window when clicked on. Once a directory is selected the path will be shown near the button to indicate a folder is set in electron-preferences.

I'll close this issue for now. If you have more questions about how to implement it, or suggestions for features on the 'file' component, please comment on #55.
