### ISSUE TITLE
Preferences Folder Filed Type multiSelections

### ISSUE THREAD

**Issue by daryl-williams** [tkambler/electron-preferences#81]
Ok, I can be pretty thick sometimes but I was finally able to figure out how to use the Folder file type to get a file dialog window. Now I would like to make that dialog window allow for multiple selections. Is there a "sections" field or some other attribute that I can use to request the file dialog allow for multiSelections?

Thanks,

Daryl

**Comment by pvrobays** [comment]
Hi Daryl

I don't know this by heart and currently not in the position to browse though the code. But I think having a quick look at how this should be implemented in Electron, and a view to the source code should help you find if it's possible.let me know if you haven't found something, then I'll have a look when I can

**Comment by pvrobays** [comment]
@daryl-williams Update:
This has been implemented in the new file type, but not in the directory/folder type.
I'll try to add it together with the new file feature, or create a new PR for it in the near future. To be continued...

**Comment by pvrobays** [comment]
Will be available in the next release
