### ISSUE TITLE
Is there a field for "File" type to select files instead of directories?

### ISSUE THREAD

**Issue by daryl-williams** [tkambler/electron-preferences#82]
I am using electron-preferences to set values for several folders and that works fine however I also need to prompt for a file selection. If I change the type to "file" instead of "directory" nothing happens. What is the correct type to popup a file selection dialog?

Thanks,

Daryl

**Comment by pvrobays** [comment]
Hi Daryl

I'm afraid the file type hasn't been implemented yet. Therefor I've created issue #55.
It should be quite simple to implement though, as it is the same logic as the folder dialog which as you state is already implemented.
So if you're up for the challenge to try and add the file type to electron-preference, just let me know in issue #55. Else I'll try to give that issue a higher priority on my todo list.

For now I'm closing this issue as it's a duplicate.

**Comment by pvrobays** [comment]
Will be available in the next release
