### ISSUE TITLE
Need access to `preferencesWindow`

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#93]
I need to call `mainWindow.setAlwaysOnTop( true, 'screen-saver' )` on the preferencesWindow. Need to add a getter

**Comment by pvrobays** [comment]
@lacymorrow Am I understanding correctly that you want the preferences window to be `alwaysOnTop` when it's opened?
Seems like a good candidate for a setting. Once had another request to easily make the prefs window modal (see issue #77).
I'll keep this ticket open to create two new settings:
- isAlwaysOnTop(: boolean)
- isModal(: boolean) + parentWindow(: BrowserWindow)

**Comment by lacymorrow** [comment]
Well, I want to do more than that like moving the window around the screen programmatically (or to an external display). I also would prefer to call `alwaysOnTop` after it has been opened. I think having access to the `browserWindow` instance would be ideal.

**Comment by pvrobays** [comment]
OK, we'll create a getter as well then for the preference window. Maybe also add an 'onShowPreferences' and 'onClosePreferences' event.
