### ISSUE TITLE
A generic button component with custom functionality

### ISSUE THREAD

**Issue by lacymorrow** [tkambler/electron-preferences#99]
Definitely a "nice-to-have".

I would like to be able to allow the user to have a button within the preferences window that can call functions (ipc back to the parent window process).

Essentially, it would be nice to have a "Reset to defaults" button, or a "Center App Window" button. Some ability to attach custom functionality to a component (to do things like IPC back to the parent window)

**Comment by pvrobays** [comment]
FYI @lacymorrow , just noticed we had an old PR open which actually implemented the IPC button: #29

The `Reset to defaults` seems maybe like an option to which can be a preference type on its own.

**Comment by lacymorrow** [comment]
Sounds good! A reset to defaults method would be welcome

**Comment by lacymorrow** [comment]
After looking further, `resetDefaults()` should be a method of electron-preferences, and the button should be separate. I'll have a PR for the button soon.

**Comment by pvrobays** [comment]
Released in 2.6.0
